name: macos-tests

on: [push]

jobs:
  debug-tests:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Get latest version of stable Rust
      run: rustup update stable
    - name: Install ganache-cli
      run: sudo npm install -g ganache-cli
    - name: Run tests in debug
      run: make test-debug
